[options]
; Run this configuration from the odoo-erp directory:
; python3 odoo/odoo-bin -c config/odoo.local.conf

addons_path = addons,odoo/addons,/home/nguyentam/Projects/FMCG_DataPlatform_End2End/services/data-source-simulators/odoo-erp/addons
data_dir = .local/odoo

db_host = localhost
db_port = 5433
db_user = odoo
db_password = fmcg_odoo_local_2026_change_me
db_name = fmcg_erp
dbfilter = ^fmcg_erp$
list_db = True

proxy_mode = False

workers = 0
max_cron_threads = 1
log_level = info
dev_mode = reload,xml
limit_time_real = 600
limit_time_cpu = 600
limit_time_real_cron = 600
